const QUESTION_SETS = [
  {
    id: "19-all",
    label: "第19回 ①＋③",
    title: "基本動詞の熟語",
    range: "UPGRADE pp.330-347",
    sourceNote: "Googleフォームのクラス・出席番号・名前入力欄を除いた40問",
    questions: [
      // 第19回 ①
      { id: 1, sourceSet: "①", sourceNo: 4, text: "Whatever may happen, you must （　） your promise.", choices: ["give", "keep", "defend", "hold"], answer: 1, translation: "何が起こっても、約束を守らなければならない。", tip: "keep a promise = 約束を守る。反対は break a promise（約束を破る）。" },
      { id: 2, sourceSet: "①", sourceNo: 5, text: "I advised him that he should keep his thoughts to himself in this situation. But he couldn't （　） his tongue.", choices: ["cease", "hold", "lose", "hide"], answer: 1, translation: "私は彼に、この状況では自分の考えを胸にしまっておくよう助言した。しかし彼は黙っていられなかった。", tip: "hold one's tongue = 黙っている、言いたいことを我慢する。" },
      { id: 3, sourceSet: "①", sourceNo: 6, text: "A：Don't tell Allan about John and Mary. You know he can't （　） a secret.\nB：OK. I got it.", choices: ["hold", "stop", "save", "keep"], answer: 3, translation: "A：アランにジョンとメアリーのことを言わないで。彼は秘密を守れないから。 B：わかった。", tip: "keep a secret = 秘密を守る。keep は『ある状態を保つ』イメージ。" },
      { id: 4, sourceSet: "①", sourceNo: 7, text: "You had better keep early （　） so you will be in good health.", choices: ["conditions", "customs", "hours", "time"], answer: 2, translation: "健康でいるためには、早寝早起きの生活をした方がよい。", tip: "keep early hours = 早寝早起きの規則正しい生活をする。" },
      { id: 5, sourceSet: "①", sourceNo: 8, text: "A：I've got to go. Thank you for everything.\nB：I'll miss you but let's （　）.", choices: ["go out together", "get along with you", "not be sorry", "keep in touch"], answer: 3, translation: "A：もう行かなくちゃ。いろいろありがとう。 B：寂しくなるけど、連絡を取り合おう。", tip: "keep in touch = 連絡を取り合う。stay in touch もほぼ同じ意味。" },
      { id: 6, sourceSet: "①", sourceNo: 9, text: "Keep your children （　） movies too often.", choices: ["of going on", "from going to", "by going for", "away from"], answer: 1, translation: "子どもたちがあまり頻繁に映画を見に行かないようにしなさい。", tip: "keep A from -ing = Aが〜するのを妨げる／防ぐ。" },
      { id: 7, sourceSet: "①", sourceNo: 10, text: "If you get too excited in an argument, you tend to （　） the main point.", choices: ["keep up with", "lose sight of", "pay attention to", "think much of"], answer: 1, translation: "議論で興奮しすぎると、要点を見失いがちだ。", tip: "lose sight of = 〜を見失う。物理的にも比喩的にも使える。" },
      { id: 8, sourceSet: "①", sourceNo: 11, text: "\"（　）! There's a car coming,\" the mother shouted to her young daughter.", choices: ["Danger", "Watch out", "Caution", "Attention"], answer: 1, translation: "『気をつけて！ 車が来ているよ』と母親は幼い娘に叫んだ。", tip: "Watch out! = 気をつけて！ Look out! も同じように警告で使える。" },
      { id: 9, sourceSet: "①", sourceNo: 12, text: "If you have any questions, please （　） to ask me any time.", choices: ["be easy", "be safe", "feel easy", "feel free"], answer: 3, translation: "質問があれば、いつでも遠慮なく私に聞いてください。", tip: "feel free to V = 遠慮なくVする。依頼や案内でよく使う表現。" },
      { id: 10, sourceSet: "①", sourceNo: 13, text: "I haven't （　） my girlfriend for more than three months.", choices: ["heard from", "listened from", "written from", "received from", "talked from"], answer: 0, translation: "私は3か月以上、彼女から連絡をもらっていない。", tip: "hear from A = Aから便り・連絡をもらう。hear of/about A は『Aについて耳にする』。" },
      { id: 11, sourceSet: "①", sourceNo: 14, text: "We （　） our restaurant ten years ago in Paris.", choices: ["made starting", "started out", "set up", "set for"], answer: 2, translation: "私たちは10年前、パリでレストランを開業した。", tip: "set up = 設立する／開業する。establish に近い。" },
      { id: 12, sourceSet: "①", sourceNo: 15, text: "It'll （　） you no harm to drink a little whisky.", choices: ["come", "do", "have", "take"], answer: 1, translation: "少量のウイスキーを飲んでも害にはならないだろう。", tip: "do A harm = Aに害を与える。do no harm = 害にならない。" },
      { id: 13, sourceSet: "①", sourceNo: 16, text: "My birthday is a month from today, that's to （　）, April 5th.", choices: ["say", "speak", "talk", "tell"], answer: 0, translation: "私の誕生日は今日から1か月後、つまり4月5日だ。", tip: "that is to say = つまり／言い換えれば。" },
      { id: 14, sourceSet: "①", sourceNo: 17, text: "Don't speak ill （　） others behind their backs.", choices: ["of", "off", "on", "only", "out"], answer: 0, translation: "陰で他人の悪口を言ってはいけない。", tip: "speak ill of A = Aの悪口を言う。反対は speak well of A。" },
      { id: 15, sourceSet: "①", sourceNo: 18, text: "As we have seen, the basis of this conclusion is, to say the （　）, vague.", choices: ["honest", "least", "more", "opinion"], answer: 1, translation: "これまで見てきたように、この結論の根拠は、控えめに言っても曖昧だ。", tip: "to say the least = 控えめに言っても。実際はもっと強く批判したい時にも使う。" },
      { id: 16, sourceSet: "①", sourceNo: 19, text: "Fortunately, she （　） the bankrupt company.", choices: ["had been hired by", "had nothing to do with", "shared nothing to", "worked desperately for"], answer: 1, translation: "幸い、彼女はその倒産した会社とは何の関係もなかった。", tip: "have nothing to do with A = Aと何の関係もない。" },
      { id: 17, sourceSet: "①", sourceNo: 20, text: "Two students （　） asleep during the class.", choices: ["began", "fell", "jumped", "led"], answer: 1, translation: "授業中に2人の生徒が眠り込んだ。", tip: "fall asleep = 眠りにつく。be asleep は『眠っている状態』。" },
      { id: 18, sourceSet: "①", sourceNo: 21, text: "The editor hit （　） a good title for a new novel by a famous writer.", choices: ["at", "over", "upon", "with"], answer: 2, translation: "編集者は、有名作家の新しい小説によい題名を思いついた。", tip: "hit upon A = Aを思いつく。come up with A に近い。" },
      { id: 19, sourceSet: "①", sourceNo: 22, text: "Allen plays the piano beautifully, but I don't like the way he always （　） in front of everyone.", choices: ["comes over", "makes out", "shows off", "turns around"], answer: 2, translation: "アレンはピアノがとても上手だが、皆の前でいつも自慢するところが好きではない。", tip: "show off = 見せびらかす／自慢する。やや否定的なニュアンスがある。" },
      { id: 20, sourceSet: "①", sourceNo: 23, text: "The clerk （　） me a call to let me know about you.", choices: ["hit", "took", "gave", "sent"], answer: 2, translation: "店員はあなたのことを知らせるために私に電話をくれた。", tip: "give A a call = Aに電話する。call A とほぼ同じ。" },

      // 第19回 ③
      { id: 21, sourceSet: "③", sourceNo: 4, text: "Whatever may happen, you must （　） your promise.", choices: ["give", "keep", "defend", "hold"], answer: 1, translation: "何が起こっても、約束を守らなければならない。", tip: "keep a promise = 約束を守る。反対は break a promise（約束を破る）。" },
      { id: 22, sourceSet: "③", sourceNo: 5, text: "I advised him that he should keep his thoughts to himself in this situation. But he couldn't （　） his tongue.", choices: ["cease", "hold", "lose", "hide"], answer: 1, translation: "私は彼に、この状況では自分の考えを胸にしまっておくよう助言した。しかし彼は黙っていられなかった。", tip: "hold one's tongue = 黙っている、言いたいことを我慢する。" },
      { id: 23, sourceSet: "③", sourceNo: 6, text: "A：Don't tell Allan about John and Mary. You know he can't （　） a secret.\nB：OK. I got it.", choices: ["hold", "stop", "save", "keep"], answer: 3, translation: "A：アランにジョンとメアリーのことを言わないで。彼は秘密を守れないから。 B：わかった。", tip: "keep a secret = 秘密を守る。keep は『ある状態を保つ』イメージ。" },
      { id: 24, sourceSet: "③", sourceNo: 7, text: "You had better keep early （　） so you will be in good health.", choices: ["conditions", "customs", "hours", "time"], answer: 2, translation: "健康でいるためには、早寝早起きの生活をした方がよい。", tip: "keep early hours = 早寝早起きの規則正しい生活をする。" },
      { id: 25, sourceSet: "③", sourceNo: 8, text: "A：I've got to go. Thank you for everything.\nB：I'll miss you but let's （　）.", choices: ["go out together", "get along with you", "not be sorry", "keep in touch"], answer: 3, translation: "A：もう行かなくちゃ。いろいろありがとう。 B：寂しくなるけど、連絡を取り合おう。", tip: "keep in touch = 連絡を取り合う。stay in touch もほぼ同じ意味。" },
      { id: 26, sourceSet: "③", sourceNo: 9, text: "When I drive, I （　） only safety in mind.", choices: ["am", "hold", "keep", "support"], answer: 2, translation: "運転するとき、私は安全だけを念頭に置いている。", tip: "keep A in mind = Aを心に留めておく／念頭に置く。" },
      { id: 27, sourceSet: "③", sourceNo: 10, text: "It is very expensive to keep （　） with the fashion.", choices: ["to", "at", "up", "by"], answer: 2, translation: "流行についていくのはとてもお金がかかる。", tip: "keep up with A = Aについていく。catch up with A は『Aに追いつく』。" },
      { id: 28, sourceSet: "③", sourceNo: 11, text: "Matty, my colleague, is very shy. She can't look （　）.", choices: ["me my eye", "at me in my eyes", "at me in eyes", "me in the eye"], answer: 3, translation: "同僚のマティはとても内気で、私の目をまっすぐ見ることができない。", tip: "look A in the eye = Aの目をまっすぐ見る。eye は単数形で使う。" },
      { id: 29, sourceSet: "③", sourceNo: 12, text: "There was nobody in the village. We （　） the whole area for hours, but could find no trace of residents.", choices: ["looked for", "searched", "sought", "saw", "witnessed"], answer: 1, translation: "村には誰もいなかった。私たちは何時間もその地域全体を捜索したが、住民の痕跡は見つからなかった。", tip: "search + 場所 = 場所を捜索する。search for + 人・物 = 人・物を探す。" },
      { id: 30, sourceSet: "③", sourceNo: 13, text: "Will you （　） after my cats while I'm away from home?", choices: ["keep", "look", "put", "catch"], answer: 1, translation: "私が留守の間、猫の世話をしてくれますか。", tip: "look after A = Aの世話をする。take care of A に近い。" },
      { id: 31, sourceSet: "③", sourceNo: 14, text: "\"（　）! There's a car coming,\" the mother shouted to her young daughter.", choices: ["Danger", "Watch out", "Caution", "Attention"], answer: 1, translation: "『気をつけて！ 車が来ているよ』と母親は幼い娘に叫んだ。", tip: "Watch out! = 気をつけて！ Look out! も同じように警告で使える。" },
      { id: 32, sourceSet: "③", sourceNo: 15, text: "If you have any questions, please （　） to ask me any time.", choices: ["be easy", "be safe", "feel easy", "feel free"], answer: 3, translation: "質問があれば、いつでも遠慮なく私に聞いてください。", tip: "feel free to V = 遠慮なくVする。依頼や案内でよく使う表現。" },
      { id: 33, sourceSet: "③", sourceNo: 16, text: "We all went to the airport to see Mr. Adams （　）.", choices: ["at", "out", "off", "up"], answer: 2, translation: "私たちは皆、アダムズ氏を見送るために空港へ行った。", tip: "see A off = Aを見送る。駅や空港での見送りによく使う。" },
      { id: 34, sourceSet: "③", sourceNo: 17, text: "We （　） our restaurant ten years ago in Paris.", choices: ["made starting", "started out", "set up", "set for"], answer: 2, translation: "私たちは10年前、パリでレストランを開業した。", tip: "set up = 設立する／開業する。establish に近い。" },
      { id: 35, sourceSet: "③", sourceNo: 18, text: "Don't speak ill （　） others behind their backs.", choices: ["of", "off", "on", "only", "out"], answer: 0, translation: "陰で他人の悪口を言ってはいけない。", tip: "speak ill of A = Aの悪口を言う。反対は speak well of A。" },
      { id: 36, sourceSet: "③", sourceNo: 19, text: "We couldn't tell one （　） the other.", choices: ["with", "to", "against", "from"], answer: 3, translation: "私たちは一方ともう一方を見分けることができなかった。", tip: "tell A from B = AとBを見分ける。distinguish A from B に近い。" },
      { id: 37, sourceSet: "③", sourceNo: 20, text: "Two students （　） asleep during the class.", choices: ["began", "fell", "jumped", "led"], answer: 1, translation: "授業中に2人の生徒が眠り込んだ。", tip: "fall asleep = 眠りにつく。be asleep は『眠っている状態』。" },
      { id: 38, sourceSet: "③", sourceNo: 21, text: "The first of May （　） on a Sunday this year.", choices: ["fell", "happened", "hit", "jumped", "stopped"], answer: 0, translation: "今年は5月1日が日曜日に当たった。", tip: "fall on + 曜日／日付 = （日付が）〜に当たる。" },
      { id: 39, sourceSet: "③", sourceNo: 22, text: "I'll pick you （　） at Sendai Station at five.", choices: ["on", "out", "up", "off"], answer: 2, translation: "5時に仙台駅であなたを迎えに行くよ。", tip: "pick A up = Aを迎えに行く／車などで拾う。" },
      { id: 40, sourceSet: "③", sourceNo: 23, text: "Allen plays the piano beautifully, but I don't like the way he always （　） in front of everyone.", choices: ["comes over", "makes out", "shows off", "turns around"], answer: 2 }
    ]
  }
];
